=pod

=encoding UTF-8

=head1 NAME

Data::HTML5Validation - Validate (and sanitize) data like HTML5 does

=head1 VERSION

version 0.001

=head1 SYNOPSIS

    use Data::HTML5Validation qw(validate);

    my $constraints = {
        email        => { type => 'email',    required => 1 },
        name         => { type => 'text'                    },
        accept_terms => { type => 'checkbox', required => 1 }
    };

    $result = validate({
        email        => '   somebody@example.com',
        name         => '',
    }, $constraints);

    # $result: {
    #     email => {
    #         valid     => 1,
    #         sanitized => 'somebody@example.com'
    #     },
    #     name => {
    #         valid => 1
    #     },
    #     accept_terms => {
    #         valid         => 0,
    #         value_missing => 1
    #     }
    # }

    $result = validate('I am not an email', { type => 'email' });

    # $result: {
    #     valid         => 0,
    #     sanitized     => 'I am not an email',
    #     type_mismatch => 1
    # }

=head1 FUNCTIONS

=head2 validate

Validates the provided value or data structure and returns the results.

    $result = validate($value, $constraints);

=for :stopwords cpan testmatrix url annocpan anno bugtracker rt cpants kwalitee diff irc mailto metadata placeholders metacpan

=head1 SUPPORT

=head2 Bugs / Feature Requests

Please report any bugs or feature requests through the issue tracker
at L<https://github.com/odyniec/p5-Data-HTML5Validation/issues>.
You will be notified automatically of any progress on your issue.

=head2 Source Code

This is open source software.  The code repository is available for
public review and contribution under the terms of the license.

L<https://github.com/odyniec/p5-Data-HTML5Validation>

  git clone https://github.com/odyniec/p5-Data-HTML5Validation.git

=head1 AUTHOR

Michal Wojciechowski <odyniec@cpan.org>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2016 by Michal Wojciechowski.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

=cut
